# Setup
title:        Aaron Karras
tagline:      Software Engineer who makes stupid (but fun) stuff.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Aaron Karras
  url:        http://akarras.com

# Gems
gems:
  - jekyll-paginate

plugins: [jekyll-paginate]

#Others
markdown: kramdown
theme: jekyll-theme-cayman